# Markdown renderer configuration
[goldmark.renderer]
unsafe = true

# Hugo includes an embedded link render hook to resolve Markdown link destinations. 
# Disabled by default, you can enable it in your site configuration:
# [goldmark.renderHooks]
#    [markup.goldmark.renderHooks.link]
#        enableDefault = true

[goldmark.extensions.passthrough]
enable = true

# LaTeX math support
# https://gohugo.io/content-management/mathematics/
[goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]

[tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4